const MenuList = [
  {
    id: 1,
    name: "RECOMENDED",
    categories: [
      {
        id: 1,
        name: "CAT1",
        items: [
          {
            id: 1,
            name: "Laska Noodles",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
          {
            id: 2,
            name: "Laska Noodles111",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
          {
            id: 3,
            name: "Laska Noodles111",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
          {
            id: 4,
            name: "Laska Noodles444",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
        ],
      },
      {
        id: 2,
        name: "CAT2",
        items: [
          {
            id: 1,
            name: "Laska Noodles",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
          {
            id: 2,
            name: "Laska Noodles111",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
          {
            id: 3,
            name: "Laska Noodles333",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "SMALL BITES",
    categories: [
      {
        id: 1,
        name: "CAT11",
        items: [
          {
            id: 1,
            name: "Laska Noodles",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
          {
            id: 2,
            name: "Laska Noodles111",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
          {
            id: 3,
            name: "Laska Noodles3333",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
        ],
      },
      {
        id: 2,
        name: "CAT22",
        items: [
          {
            id: 1,
            name: "Laska Noodles",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
          {
            id: 2,
            name: "Laska Noodles111",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "MAINS",
    categories: [
      {
        id: 1,
        name: "CAT13",
        items: [
          {
            id: 1,
            name: "Laska Noodles",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
          {
            id: 2,
            name: "Laska Noodles111",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
          {
            id: 3,
            name: "Laska Noodles3333",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
        ],
      },
      {
        id: 2,
        name: "CAT23",
        items: [
          {
            id: 1,
            name: "Laska Noodles",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
          {
            id: 2,
            name: "Laska Noodles111",
            img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: [
              { id: 1, name: "AddChicken", selected: false, price: 1.5 },
              { id: 2, name: "AddTofu", selected: false, price: 1.5 },
              { id: 3, name: "AddShrimp", selected: false, price: 1.5 },
              {
                id: 4,
                name: "AddHoneyRoastedPork",
                selected: false,
                price: 1.5,
              },
              { id: 5, name: "ExtraChicken", selected: false, price: 1.5 },
              { id: 6, name: "ExtraTofu", selected: false, price: 1.5 },
              { id: 7, name: "ExtraShrimp", selected: false, price: 1.5 },
              { id: 8, name: "ExtraPork", selected: false, price: 1.5 },
              { id: 9, name: "NoProtein", selected: false, price: 1.5 },
              { id: 10, name: "NoUtensils", selected: false, price: 1.5 },
              { id: 11, name: "SpecialInstructions" },
            ],
          },
        ],
      },
    ],
  },
];

const cartList = [
  {
    menuId: 1,
    items: [
      {
        count: 2,
        item: {
          id: 1,
          img: "https://www.recipetineats.com/wp-content/uploads/2020/07/Laksa_1-SQ.jpg",
          name: "test",
          price: 22,
          decription: "test description",
          options: [{ id: 1 }, { id: 2 }],
        },
      },
    ],
  },
];
module.exports = { MenuList, cartList };
