const MenuList = [
  {
    id: 1,
    name: "RECOMENDED",
    categories: [
      {
        id: 1,
        name: "CAT1",
        items: [
          {
            id: 1,
            name: "Laska Noodles",
            img: "https://avegtastefromatoz.com/wp-content/uploads/2022/01/Noodle-steps-FI.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg",
            options: {
              AddChicken: false,
              AddTofu: false,
              AddShrimp: false,
              AddHoneyRoastedPork: false,
              ExtraChicken: false,
              ExtraTofu: false,
              ExtraShrimp: false,
              ExtraPork: false,
              NoProtein: false,
              NoUtensils: false,
              SpecialInstructions: "",
            },
          },
          {
            id: 2,
            name: "Laska Noodles111",
            img: "https://avegtastefromatoz.com/wp-content/uploads/2022/01/Noodle-steps-FI.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: {
              AddChicken: false,
              AddTofu: false,
              AddShrimp: false,
              AddHoneyRoastedPork: false,
              ExtraChicken: false,
              ExtraTofu: false,
              ExtraShrimp: false,
              ExtraPork: false,
              NoProtein: false,
              NoUtensils: false,
              SpecialInstructions: "",
            },
          },
        ],
      },
      {
        id: 2,
        name: "CAT2",
        items: [
          {
            id: 1,
            name: "Laska Noodles",
            img: "https://avegtastefromatoz.com/wp-content/uploads/2022/01/Noodle-steps-FI.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg",
            options: {
              AddChicken: false,
              AddTofu: false,
              AddShrimp: false,
              AddHoneyRoastedPork: false,
              ExtraChicken: false,
              ExtraTofu: false,
              ExtraShrimp: false,
              ExtraPork: false,
              NoProtein: false,
              NoUtensils: false,
              SpecialInstructions: "",
            },
          },
          {
            id: 2,
            name: "Laska Noodles111",
            img: "https://avegtastefromatoz.com/wp-content/uploads/2022/01/Noodle-steps-FI.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: {
              AddChicken: false,
              AddTofu: false,
              AddShrimp: false,
              AddHoneyRoastedPork: false,
              ExtraChicken: false,
              ExtraTofu: false,
              ExtraShrimp: false,
              ExtraPork: false,
              NoProtein: false,
              NoUtensils: false,
              SpecialInstructions: "",
            },
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "SMALL BITES",
    categories: [
      {
        id: 1,
        name: "CAT1",
        items: [
          {
            id: 1,
            name: "Laska Noodles",
            img: "https://avegtastefromatoz.com/wp-content/uploads/2022/01/Noodle-steps-FI.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg",
            options: {
              AddChicken: false,
              AddTofu: false,
              AddShrimp: false,
              AddHoneyRoastedPork: false,
              ExtraChicken: false,
              ExtraTofu: false,
              ExtraShrimp: false,
              ExtraPork: false,
              NoProtein: false,
              NoUtensils: false,
              SpecialInstructions: "",
            },
          },
          {
            id: 2,
            name: "Laska Noodles111",
            img: "https://avegtastefromatoz.com/wp-content/uploads/2022/01/Noodle-steps-FI.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: {
              AddChicken: false,
              AddTofu: false,
              AddShrimp: false,
              AddHoneyRoastedPork: false,
              ExtraChicken: false,
              ExtraTofu: false,
              ExtraShrimp: false,
              ExtraPork: false,
              NoProtein: false,
              NoUtensils: false,
              SpecialInstructions: "",
            },
          },
        ],
      },
      {
        id: 2,
        name: "CAT2",
        items: [
          {
            id: 1,
            name: "Laska Noodles",
            img: "https://avegtastefromatoz.com/wp-content/uploads/2022/01/Noodle-steps-FI.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg",
            options: {
              AddChicken: false,
              AddTofu: false,
              AddShrimp: false,
              AddHoneyRoastedPork: false,
              ExtraChicken: false,
              ExtraTofu: false,
              ExtraShrimp: false,
              ExtraPork: false,
              NoProtein: false,
              NoUtensils: false,
              SpecialInstructions: "",
            },
          },
          {
            id: 2,
            name: "Laska Noodles111",
            img: "https://avegtastefromatoz.com/wp-content/uploads/2022/01/Noodle-steps-FI.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: {
              AddChicken: false,
              AddTofu: false,
              AddShrimp: false,
              AddHoneyRoastedPork: false,
              ExtraChicken: false,
              ExtraTofu: false,
              ExtraShrimp: false,
              ExtraPork: false,
              NoProtein: false,
              NoUtensils: false,
              SpecialInstructions: "",
            },
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "MAINS",
    categories: [
      {
        id: 1,
        name: "CAT1",
        items: [
          {
            id: 1,
            name: "Laska Noodles",
            img: "https://avegtastefromatoz.com/wp-content/uploads/2022/01/Noodle-steps-FI.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg",
            options: {
              AddChicken: { selected: false, price: 1.5 },
              AddTofu: { selected: false, price: 1.5 },
              AddShrimp: { selected: false, price: 1.5 },
              AddHoneyRoastedPork: { selected: false, price: 1.5 },
              ExtraChicken: { selected: false, price: 1.5 },
              ExtraTofu: { selected: false, price: 1.5 },
              ExtraShrimp: { selected: false, price: 1.5 },
              ExtraPork: { selected: false, price: 1.5 },
              NoProtein: { selected: false, price: 1.5 },
              NoUtensils: { selected: false, price: 1.5 },
              SpecialInstructions: "",
            },
          },
          {
            id: 2,
            name: "Laska Noodles111",
            img: "https://avegtastefromatoz.com/wp-content/uploads/2022/01/Noodle-steps-FI.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: {
              AddChicken: { selected: false, price: 1.5 },
              AddTofu: { selected: false, price: 1.5 },
              AddShrimp: { selected: false, price: 1.5 },
              AddHoneyRoastedPork: { selected: false, price: 1.5 },
              ExtraChicken: { selected: false, price: 1.5 },
              ExtraTofu: { selected: false, price: 1.5 },
              ExtraShrimp: { selected: false, price: 1.5 },
              ExtraPork: { selected: false, price: 1.5 },
              NoProtein: { selected: false, price: 1.5 },
              NoUtensils: { selected: false, price: 1.5 },
              SpecialInstructions: "",
            },
          },
        ],
      },
      {
        id: 2,
        name: "CAT2",
        items: [
          {
            id: 1,
            name: "Laska Noodles",
            img: "https://avegtastefromatoz.com/wp-content/uploads/2022/01/Noodle-steps-FI.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg",
            options: {
              AddChicken: { selected: false, price: 1.5 },
              AddTofu: { selected: false, price: 1.5 },
              AddShrimp: { selected: false, price: 1.5 },
              AddHoneyRoastedPork: { selected: false, price: 1.5 },
              ExtraChicken: { selected: false, price: 1.5 },
              ExtraTofu: { selected: false, price: 1.5 },
              ExtraShrimp: { selected: false, price: 1.5 },
              ExtraPork: { selected: false, price: 1.5 },
              NoProtein: { selected: false, price: 1.5 },
              NoUtensils: { selected: false, price: 1.5 },
              SpecialInstructions: "",
            },
          },
          {
            id: 2,
            name: "Laska Noodles111",
            img: "https://avegtastefromatoz.com/wp-content/uploads/2022/01/Noodle-steps-FI.jpg",
            price: "13.0",
            decription:
              "Creamy satay peanut sauce wide egg noodlesm soft-bioled egg1111",
            options: {
              AddChicken: { selected: false, price: 1.5 },
              AddTofu: { selected: false, price: 1.5 },
              AddShrimp: { selected: false, price: 1.5 },
              AddHoneyRoastedPork: { selected: false, price: 1.5 },
              ExtraChicken: { selected: false, price: 1.5 },
              ExtraTofu: { selected: false, price: 1.5 },
              ExtraShrimp: false,
              ExtraPork: false,
              NoProtein: false,
              NoUtensils: false,
              SpecialInstructions: "",
            },
          },
        ],
      },
    ],
  },
];

const cart = [];
module.exports = { MenuList, cart };
